### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by asclines**
This Pull Request brings in [ESDoc](https://esdoc.org). See #8 
Currently, the only source code documented is the `api/users` section. Hopefully, this is sufficient enough to serve as an example.

This pull request brings in the `npm` command: `npm run docs` which generates all the doc HTML pages and places them into the `/docs/` folder. It is in my opinion that they should stay there and the GitHub pages are served out of that folder rather than on their own branch. That way the documentation follows the source code. 

It is my hope that this documentation ends up going beyond the source code and provides information for things such as contributions so that future developers can be easily onboarded to this project. 

Before continuing, I would like feedback on what there is so far. To see the docs, open `/docs/index.html` in your browser and you are good to go.

Note: This is just the default theme for ESDocs, if we decide to stick with ESDoc, theming can be adjusted.

**All HTML files in this PR are generated**

### CODE REVIEW

**Comment by NilsG-S** [comment]
@asclines I had to add `"lint": false` to `.esdoc.json` because I was getting a `Cannot read property 'length' of undefined` error when running `npm run docs`. There's probably a better solution as outlined here: https://github.com/esdoc/esdoc/issues/384

**Comment by asclines** [comment]
@NilsG-S I was getting that error too but ignoring it as it wasn't affecting anything and I was waiting for confirmation that we would be going this route before fine-tuning ESDoc

**Comment by NilsG-S** [comment]
@asclines That makes sense. Were you planning to use [manual integration](https://esdoc.org/manual/usage/feature.html#integration-manual) to include other kinds of documentation?

Also, was the idea that developers would run `esdoc` every time they make a change, thus updating the documentation?

I've looked over the output and I really like it. Would there be any point to me actually looking over the code in the PR?

**Comment by asclines** [comment]
@NilsG-S Yes, I was planning on looking into extensions with ESDoc in the future. I just plan to take this one step at a time, by first picking our a solid doc generator that allows for any future customization and additions without too much extra work.

As for looking at the code, nah. The output of the HTML is more important. But if you want to look at the `api/users` source code to see examples of how to format comments for the docs go for it.

As for when the developer should run `npm run docs` I'm not sure and that requires more discussion to be talked about in Slack.

**Pull request merged**
