### PR TITLE
Winston

### PR DESCRIPTION
**Pull request by asclines**
# WIP

I am bringing up this pull request to get suggestions. 
First off, I have created a new folder in the root directory; `common`.  In here I hope to have the shared codebase between the front end and the back end. Here we can put things such as validators, logging, and other util methods. 

My concern is, would this be worth any potential trouble? All code here would have to be browser capable or transformed with Babel (unless I am mistaken).

If not, I will refactor the contents of `common` into the `api` folder.

To allow this `common` folder to be used by the front end, I believe Webpack will have to be updated, if so, @NilsG-S can you handle that?

And if #4 goes through, it will have to account for this as well.

### CODE REVIEW

**Comment by NilsG-S** [comment]
@asclines When you say that Webpack would have to be updated, do you mean including the `common` folder as a place to look for imports? Or did you have something else in mind?

**Comment by asclines** [comment]
@NilsG-S I believe that is exactly what needs to be done. Is that all it takes to so that both `api` and `app` use it?

**Comment by NilsG-S** [comment]
@asclines As far as I know

**Comment by asclines** [comment]
@NilsG-S any more thoughts/comments on this?

**Comment by asclines** [comment]
Closing as we are no longer going this way.

**Pull request closed without merging**
