### PR TITLE
Packages and Linting

### PR DESCRIPTION
**Pull request by NilsG-S**
Changes are as follows:

- Upgraded to newer packages
- Updated routing to support API changes in React Router V4
- Linted files
- Fixed testing errors that were caused by other changes

### CODE REVIEW

**Comment by NilsG-S** [comment]
So I'm pretty sure I know what's wrong. Basically the problem with the `history` module results from a conflict between `grommet` and `react-router-dom`. Both will install it, but installing `grommet` first means that it is submoduled under that package, rather than under `react-router-dom`, which doesn't like that.

**Comment by asclines** [comment]
@NilsG-S continuing this conversation in Slack.

**Comment by NilsG-S** [comment]
@asclines So basically instead we're caching the place where NPM stores recently installed packages? That would have the same result of reducing build time (although to a lesser extent), while doing a fresh installation for each build.

**Comment by asclines** [comment]
The important part is that `.npm` doesn't store compiled native modules. That's what I believe caused the tests to constantly fail on the second version of node. Incompatible binaries were being cached.

**Comment by NilsG-S** [comment]
Sounds good, I'll go ahead and merge it

**Pull request merged**
